version: '3'

services:
  traefik:
    image: traefik:v2.6
    command:
      # - --api.insecure=true
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.shrecksecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.web.http.redirections.entrypoint.to=shrecksecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web
      - back
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.docker.network=web
        - traefik.http.routers.traefik-dash.tls=true
        - traefik.http.services.traefik-dash.loadbalancer.server.port=8080
        - traefik.http.routers.traefik-dash.entrypoints=shrecksecure
        - traefik.http.routers.traefik-dash.service=api@internal
        - traefik.http.routers.traefik-dash.rule=Host(`traefik.uwu`)
        - traefik.http.routers.traefik-dash.middlewares=basic-auth
        - traefik.http.middlewares.basic-auth.basicauth.users=admin:$$apr1$$nN1cqEn0$$/.R9RmImw2ovsp6X1Gavf.,user:$$apr1$$pvwSLi7k$$5DHFUg2SrTkVfeN5LZjpW/
      placement:
        constraints:
          - node.role==manager
  wordpress:
    image: wordpress
    networks:
      - back
      - database
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root  #très sécur <3
      WORDPRESS_DB_PASSWORD: root #très sécur <3
      WORDPRESS_DB_NAME: wordpress_swarm
    volumes:
      - wordpress:/var/www/html
    deploy:
      replicas: 5
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.wordpress.entrypoints=shrecksecure"
        - "traefik.http.routers.wordpress.rule=Host(`wordpress.uwu`)"
        - "traefik.http.routers.wordpress.tls=true"
        - "traefik.http.services.wordpress.loadbalancer.server.port=80"
        - "traefik.http.services.wordpress.loadbalancer.sticky=true"
        - "traefik.http.services.wordpress.loadbalancer.sticky.cookie.name=worpress_traefik_sticky"
        - "traefik.http.services.wordpress.loadbalancer.sticky.cookie.httponly=true"
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wordpress_swarm
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    volumes:
      - db:/var/lib/mysql
    networks:
      - database
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
volumes:
  wordpress:
  db:

networks:
  web:
    driver: overlay
  back:
    internal: true
  database:
    internal: true
